### ISSUE TITLE
Glitter hooks

### ISSUE THREAD

**Issue by eternalmoon1234** [Milo123459/glitter#33]
Idea: make an option in glitter to run a specific command before pushing

Reason: When I use glitter, I want to run my lint script before pushing

Thank you!

**Comment by Milo123459** [comment]
I have implemented a basic version of Glitter hooks now. The usage is simple:
Define a custom task
Reference custom task in `hooks`
New flags: `--no-verify` or `-n` - don't run hooks

**Comment by eternalmoon1234** [comment]
awesome, you should add it to the docs

**Comment by Milo123459** [comment]
Done
